feat: add controller
Kolobok37/java-shareit pull request #1
Opened 2023-10-22 18:58 UTC by Kolobok37

2023-10-23 18:03 UTC, Yang-Pi requested changes

2023-10-23 18:03 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private User user;
По ТЗ это поле нужно назвать owner, хоть и не так явно)

> Например, вы можете не захотеть показывать пользователям владельца вещи (поле owner)...

2023-10-23 18:03 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private ArrayList<Booking> reservation;
Лучше используй интерфейсы для типов поле - List в этом случае

2023-10-23 18:03 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        item.setUser(MapperUser.mapToUserDto(userStorageInMemory.getUser(userId)));
В методе validationUser ты уже доставал из хранилища user по id, поэтому не нужно повторно ходить в хранилище, сохрани его в локальной переменной

2023-10-23 18:03 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        itemStorage.updateItem(newItem);
Метод update используется для PATCH запроса, который подразумевает частичное обновление записи, те item в аргументе можете содержать только имя. При текущей же реализации объект обновляется полностью, те будет записано только имя

2023-10-23 18:03 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        item.setUser(MapperUser.mapToUserDto(userStorageInMemory.getUser(userId)));
Для Dto объекта будет достаточно просто id юзера, не обязательно полностью объект возвращать

2023-10-23 18:03 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +public class UserService {
См. комментарии к ItemService, потому что почти все те же замечания

2023-10-23 18:03 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        itemStorage.updateItem(newItem);
UPD: вижу реализацию в ItemStorrage. Отмена комментария выше) но лучше вынеси newValue oldValue именно в сервис, потому что хранилище не знает разницу между PUT и PATCH запросами

2023-10-23 18:03 UTC, Yang-Pi commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    private void validationItem(ItemDto item) {
И я тебе +- настоятельно рекомендую использовать валидации на уровне модели. Почему? У этого есть как минимум один важный бенефит - фильтрация на уровне запроса, те до выполнения сервиса даже не дойдет, те приложение выдержит более высокую нагрузку.

2023-10-25 22:32 UTC, Kolobok37 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        item.setUser(MapperUser.mapToUserDto(userStorageInMemory.getUser(userId)));
Пока решил не менять dto, насколько понимаю, это будет задание следующего модуля

2023-10-26 16:36 UTC, Yang-Pi approved these changes

2023-10-26 20:32 UTC, merged